//! MP3 decode against the PCM the encoder was given: length after gapless
//! trimming, channel order, waveform correlation, auto-detection with and
//! without an ID3 tag, and what damaged, truncated and tag-only streams do.
//!
//! Fixtures are synthetic, generated by `tests/fixtures/generate.sh`; see
//! `tests/fixtures/MANIFEST.md` for the matrix and provenance.

use phx_audio::{Audio, AudioError};

const BASE: &[u8] = include_bytes!("fixtures/mp3_base16.wav");
const STEREO_128K: &[u8] = include_bytes!("fixtures/mp3_stereo_128k.mp3");
const MONO_VBR: &[u8] = include_bytes!("fixtures/mp3_mono_vbr.mp3");
const ID3: &[u8] = include_bytes!("fixtures/mp3_id3.mp3");

/// Pearson correlation of two equally long signals.
fn correlation(a: &[f32], b: &[f32]) -> f64 {
    assert_eq!(a.len(), b.len());
    let mean = |x: &[f32]| x.iter().map(|&v| f64::from(v)).sum::<f64>() / x.len() as f64;
    let (ma, mb) = (mean(a), mean(b));
    let (mut sab, mut saa, mut sbb) = (0.0, 0.0, 0.0);
    for (&x, &y) in a.iter().zip(b) {
        let (x, y) = (f64::from(x) - ma, f64::from(y) - mb);
        sab += x * y;
        saa += x * x;
        sbb += y * y;
    }
    sab / (saa * sbb).sqrt()
}

fn assert_matches_source(decoded: &Audio, source_channels: &[&[f32]]) {
    let source = Audio::from_wav_bytes(BASE).unwrap();
    assert_eq!(decoded.sample_rate(), source.sample_rate());
    assert_eq!(decoded.channel_count(), source_channels.len());
    // Gapless trimming leaves exactly the encoder's input length.
    assert_eq!(decoded.frames(), source.frames());
    for (channel, expected) in source_channels.iter().enumerate() {
        let r = correlation(decoded.channel(channel), expected);
        assert!(r > 0.99, "channel {channel} correlates {r} with its source");
    }
}

#[test]
fn stereo_128k_reproduces_both_tones_in_order() {
    let source = Audio::from_wav_bytes(BASE).unwrap();
    let decoded = Audio::from_mp3_bytes(STEREO_128K).expect("MP3 fixture must decode");
    assert_matches_source(&decoded, &[source.channel(0), source.channel(1)]);
    // The channels carry different tones, so a swapped order would show.
    assert!(correlation(decoded.channel(0), source.channel(1)) < 0.5);
}

#[test]
fn mono_vbr_reproduces_the_downmix() {
    let source = Audio::from_wav_bytes(BASE).unwrap();
    // ffmpeg's `-ac 1` averages the two channels; the fixture was made that way.
    let mix: Vec<f32> = source
        .channel(0)
        .iter()
        .zip(source.channel(1))
        .map(|(l, r)| 0.5 * (l + r))
        .collect();
    let decoded = Audio::from_mp3_bytes(MONO_VBR).expect("MP3 fixture must decode");
    assert_matches_source(&decoded, &[&mix]);
}

#[test]
fn id3_tagged_stream_decodes_the_same_audio() {
    let plain = Audio::from_mp3_bytes(STEREO_128K).unwrap();
    let tagged = Audio::from_mp3_bytes(ID3).unwrap();
    assert_eq!(tagged.frames(), plain.frames());
    for channel in 0..2 {
        assert!(correlation(plain.channel(channel), tagged.channel(channel)) > 0.999);
    }
}

#[test]
fn auto_detection_routes_frame_first_and_tagged_streams() {
    for bytes in [STEREO_128K, MONO_VBR, ID3] {
        let detected = Audio::from_bytes(bytes).expect("MP3 must auto-detect");
        let direct = Audio::from_mp3_bytes(bytes).unwrap();
        assert_eq!(detected.sample_rate(), direct.sample_rate());
        assert_eq!(detected.channel_count(), direct.channel_count());
        for channel in 0..direct.channel_count() {
            assert_eq!(detected.channel(channel), direct.channel(channel));
        }
    }
}

/// A minimal ID3v2.3 tag: header, one TIT2 frame, no footer.
fn id3v2_tag() -> Vec<u8> {
    let frame = [b"TIT2".as_slice(), &[0, 0, 0, 5, 0, 0], &[0], b"tone"].concat();
    let size = frame.len();
    let mut tag = b"ID3\x03\x00\x00".to_vec();
    tag.extend_from_slice(&[
        (size >> 21) as u8 & 0x7F,
        (size >> 14) as u8 & 0x7F,
        (size >> 7) as u8 & 0x7F,
        size as u8 & 0x7F,
    ]);
    tag.extend_from_slice(&frame);
    tag
}

#[test]
fn an_id3_tag_in_front_of_flac_still_routes_to_flac() {
    let flac = include_bytes!("fixtures/flac_level5.flac");
    assert_eq!(Audio::from_bytes(flac).unwrap().channel_count(), 2);
    let tagged = [id3v2_tag().as_slice(), flac].concat();
    let decoded = Audio::from_bytes(&tagged).expect("tagged FLAC must decode as FLAC");
    let plain = Audio::from_flac_bytes(flac).unwrap();
    assert_eq!(decoded.frames(), plain.frames());
    assert_eq!(decoded.channel(1), plain.channel(1));
}

#[test]
fn other_mpeg_layers_and_adts_are_not_taken_for_mp3() {
    // ADTS AAC, Layer II, Layer I: same sync bits, other layer indices.
    for head in [
        b"\xFF\xF1\x50\x80",
        b"\xFF\xFD\x90\x00",
        b"\xFF\xFF\x90\x00",
    ] {
        assert_eq!(
            Audio::from_bytes(head).unwrap_err(),
            AudioError::UnrecognizedFormat,
            "{head:?}"
        );
    }
    assert_eq!(
        Audio::from_bytes(b"\xFF\x00\x00\x00").unwrap_err(),
        AudioError::UnrecognizedFormat
    );
}

#[test]
fn a_frame_header_followed_by_garbage_is_malformed() {
    assert!(matches!(
        Audio::from_bytes(b"\xFF\xFB\x90\x00garbage"),
        Err(AudioError::MalformedMp3(_) | AudioError::UnsupportedMp3 { .. })
    ));
}

#[test]
fn a_tag_with_no_frames_is_an_error() {
    let mut tag = id3v2_tag();
    tag.extend_from_slice(&[0; 64]);
    assert!(matches!(
        Audio::from_bytes(&tag),
        Err(AudioError::MalformedMp3(_) | AudioError::UnsupportedMp3 { .. })
    ));
}

#[test]
fn a_truncated_stream_decodes_what_it_has() {
    // The cut lands mid-frame; the demuxer ends the stream there. Only the
    // start trim applies (the end trim needs the frame count the Xing
    // header declared, which no longer matches), so the count is not exact.
    let cut = &STEREO_128K[..STEREO_128K.len() / 3];
    let partial = Audio::from_mp3_bytes(cut).unwrap();
    let whole = Audio::from_mp3_bytes(STEREO_128K).unwrap();
    assert!(partial.frames() > 0 && partial.frames() < whole.frames());
}

#[test]
fn a_damaged_frame_is_skipped_and_the_rest_decodes() {
    let whole = Audio::from_mp3_bytes(STEREO_128K).unwrap();
    let mut damaged = STEREO_128K.to_vec();
    let middle = damaged.len() / 2;
    for byte in &mut damaged[middle..middle + 24] {
        *byte = 0xA5;
    }
    let decoded = Audio::from_mp3_bytes(&damaged).expect("a damaged frame must not abort the file");
    assert!(decoded.frames() > whole.frames() / 2);
    // The first half of the file is untouched and decodes the same.
    let n = whole.frames() / 4;
    assert_eq!(&decoded.channel(0)[..n], &whole.channel(0)[..n]);
}
